apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: elasticsearch
    version: v1
    run: elasticsearch
  name: elasticsearch
  namespace: jiomeetns
  resourceVersion: "1686694"
  selfLink: /apis/apps/v1/namespaces/jiomeetns/deployments/elasticsearch
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: elasticsearch
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch
        version: v1
        run: elasticsearch
    spec:
      containers:
      - env:
        - name: discovery.type
          value: single-node
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        ports:
        - containerPort: 9200
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-jiomeetns
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: elasticsearch
    app: elasticsearch
    version: v1
  name: elasticsearch
  namespace: jiomeetns
  resourceVersion: "1686771"
  selfLink: /api/v1/namespaces/jiomeetns/services/elasticsearch
spec:
  ports:
  - nodePort: 30820
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    run: elasticsearch
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: kibana
    app: kibana
    version: v1
  name: kibana
  namespace: jiomeetns
  resourceVersion: "1687121"
  selfLink: /api/v1/namespaces/jiomeetns/services/kibana
spec:
  ports:
  - nodePort: 31944
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    run: kibana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: kibana
    app: kibana
    version: v1
  name: kibana
  namespace: jiomeetns
  resourceVersion: "1686853"
  selfLink: /apis/apps/v1/namespaces/jiomeetns/deployments/kibana
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: kibana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: kibana
        app: kibana
        version: v1
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        image: docker.elastic.co/kibana/kibana:6.2.1
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5601
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-jiomeetns
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30