apiVersion: v1
kind: Service
metadata:
  name: metrics-minion
  namespace: kafka
  labels: &labels
    app: kafka-minion
    type: openmetrics
spec:
  selector: *labels
  ports:
  - name: http
    port: 8080
